pipeline {
    agent any

    parameters {
        string(defaultValue: "Name", description: "Enter custom deployment name", name: "deployName")
        choice(choices: ['EU-WEST-2A', 'EU-WEST-2B', 'EU-WEST-2C '], description: "Select an Availabiliy Zone", name: "AZName")
        booleanParam(defaultValue: "false", description: "Tick to Confirm Deploy", name: "boolAns")
    }

    stages {
        stage("Input") {
            steps{
                echo "Name of Deployment is: ${params.deployName}"
            }
        }
        stage("Choice") {
            steps{
                echo "Selected Availability Zone is: ${params.AVName}"
            }
        }
        stage("Bool") {
            steps{
                echo "Confirm Deployment: ${params.boolAns}"
            }
        }
    }
}